apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-xtjrvglz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-xtjrvglz 
  name: go-xtjrvglz
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-xtjrvglz
    weight: 100 
